## Week 7
## Exercise 1 – Association Rule Mining

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as st

### Q1) Use the “groceries.csv” dataset and answer the following

In [2]:
df = pd.read_table("groceries.csv", header=None)
df

                                                      0
0     citrus fruit,semi-finished bread,margarine,rea...
1                          tropical fruit,yogurt,coffee
2                                            whole milk
3           pip fruit,yogurt,cream cheese ,meat spreads
4     other vegetables,whole milk,condensed milk,lon...
...                                                 ...
9830  sausage,chicken,beef,hamburger meat,citrus fru...
9831                                  cooking chocolate
9832  chicken,citrus fruit,other vegetables,butter,y...
9833  semi-finished bread,bottled water,soda,bottled...
9834  chicken,tropical fruit,other vegetables,vinega...

[9835 rows x 1 columns]

### Q2)  How many transactions and items are there in the data set?

In [3]:
print(f"Total transactions = {df.shape[0]}")

lst = []
df[0].map(lambda x: lst.append(len(x.split(","))))
print(f"Total items = {max(lst)}")

Total transactions = 9835
Total items = 32

### Q3) Prepare the data for finding association rules. Each transaction will contain a list of item in the transaction

In [4]:
df[0] = df[0].apply(lambda x: x.split(","))
df

                                                      0
0     [citrus fruit, semi-finished bread, margarine,...
1                      [tropical fruit, yogurt, coffee]
2                                          [whole milk]
3      [pip fruit, yogurt, cream cheese , meat spreads]
4     [other vegetables, whole milk, condensed milk,...
...                                                 ...
9830  [sausage, chicken, beef, hamburger meat, citru...
9831                                [cooking chocolate]
9832  [chicken, citrus fruit, other vegetables, butt...
9833  [semi-finished bread, bottled water, soda, bot...
9834  [chicken, tropical fruit, other vegetables, vi...

[9835 rows x 1 columns]

### Q4) Use Python library mlxtend and convert the transactions into a format that can be used in the Apriori method for finding frequent itemsets.

In [5]:
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules

te = TransactionEncoder()
te_ary = te.fit(df[0]).transform(df[0])
df_ = pd.DataFrame(te_ary, columns=te.columns_)
df_

,Instant food products,UHT-milk,abrasive cleaner,artif. sweetener,baby cosmetics,baby food,bags,baking powder,bathroom cleaner,beef,...,turkey,vinegar,waffles,whipped/sour cream,whisky,white bread,white wine,whole milk,yogurt,zwieback
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9830,False,False,False,False,False,False,False,False,False,True,...,False,False,False,True,False,False,False,True,False,False
9831,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9832,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
9833,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9834,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False

### Q5) Find top selling items with minimum support of 2%.

In [6]:
apriori(df_, min_support=0.02, use_colnames=True).sort_values(by="support", ascending=False)

     support                         itemsets
57  0.255516                     (whole milk)
39  0.193493               (other vegetables)
43  0.183935                     (rolls/buns)
49  0.174377                           (soda)
58  0.139502                         (yogurt)
..       ...                              ...
75  0.020539        (frankfurter, whole milk)
60  0.020437       (bottled beer, whole milk)
76  0.020437  (frozen vegetables, whole milk)
96  0.020437      (tropical fruit, pip fruit)
67  0.020031       (other vegetables, butter)

[122 rows x 2 columns]

### Q6) Find all frequent itemsets with minimum support of 5%

In [7]:
apriori(df_, min_support=0.05, use_colnames=True)

     support                        itemsets
0   0.052466                          (beef)
1   0.080529                  (bottled beer)
2   0.110524                 (bottled water)
3   0.064870                   (brown bread)
4   0.055414                        (butter)
5   0.077682                   (canned beer)
6   0.082766                  (citrus fruit)
7   0.058058                        (coffee)
8   0.053279                          (curd)
9   0.063447                 (domestic eggs)
10  0.058973                   (frankfurter)
11  0.072293         (fruit/vegetable juice)
12  0.058566                     (margarine)
13  0.052364                       (napkins)
14  0.079817                    (newspapers)
15  0.193493              (other vegetables)
16  0.088968                        (pastry)
17  0.075648                     (pip fruit)
18  0.057651                          (pork)
19  0.183935                    (rolls/buns)
20  0.108998               (root vegetables)
21  0.093950                       (sausage)
22  0.098526                 (shopping bags)
23  0.174377                          (soda)
24  0.104931                (tropical fruit)
25  0.071683            (whipped/sour cream)
26  0.255516                    (whole milk)
27  0.139502                        (yogurt)
28  0.074835  (other vegetables, whole milk)
29  0.056634        (rolls/buns, whole milk)
30  0.056024            (yogurt, whole milk)

### Q7) Find all frequent itemsets of length 2 with minimum support of 2%

In [8]:
temp = apriori(df_, min_support=0.02, use_colnames=True)

temp["length"] = temp["itemsets"].map(lambda x: len(list(x)))
temp.loc[temp["length"] == 2, :]

      support                           itemsets  length
59   0.021251                 (beef, whole milk)       2
60   0.020437         (bottled beer, whole milk)       2
61   0.024809  (other vegetables, bottled water)       2
62   0.024199        (rolls/buns, bottled water)       2
63   0.028978              (soda, bottled water)       2
..        ...                                ...     ...
115  0.042298       (tropical fruit, whole milk)       2
116  0.029283           (tropical fruit, yogurt)       2
117  0.032232   (whipped/sour cream, whole milk)       2
118  0.020742       (whipped/sour cream, yogurt)       2
119  0.056024               (yogurt, whole milk)       2

[61 rows x 3 columns]

### Q8) Find the top 10 association rules with minimum support of 2%, sorted by confidence in descending order

In [20]:
temp = apriori(df_, min_support=0.02, use_colnames=True)
temp_ = association_rules(temp, metric="lift", min_threshold=1)
temp_.sort_values(by="confidence", ascending=False).head(10)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
120,"(other vegetables, yogurt)",(whole milk),0.043416,0.255516,0.022267,0.512881,2.007235,0.011174,1.528340
16,(butter),(whole milk),0.055414,0.255516,0.027555,0.497248,1.946053,0.013395,1.480817
24,(curd),(whole milk),0.053279,0.255516,0.026131,0.490458,1.919481,0.012517,1.461085
114,"(other vegetables, root vegetables)",(whole milk),0.047382,0.255516,0.023183,0.489270,1.914833,0.011076,1.457687
116,"(root vegetables, whole milk)",(other vegetables),0.048907,0.193493,0.023183,0.474012,2.449770,0.013719,1.533320
28,(domestic eggs),(whole milk),0.063447,0.255516,0.029995,0.472756,1.850203,0.013783,1.412030
108,(whipped/sour cream),(whole milk),0.071683,0.255516,0.032232,0.449645,1.759754,0.013916,1.352735
90,(root vegetables),(whole milk),0.108998,0.255516,0.048907,0.448694,1.756031,0.021056,1.350401
51,(root vegetables),(other vegetables),0.108998,0.193493,0.047382,0.434701,2.246605,0.026291,1.426693
32,(frozen vegetables),(whole milk),0.048094,0.255516,0.020437,0.424947,1.663094,0.008149,1.294636

### Q9) Find association rules with minimum support of 2% and lift of more than 1.0

In [13]:
temp = apriori(df_, min_support=0.02, use_colnames=True)
association_rules(temp, metric="lift", min_threshold=1)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(beef),(whole milk),0.052466,0.255516,0.021251,0.405039,1.585180,0.007845,1.251315
1,(whole milk),(beef),0.255516,0.052466,0.021251,0.083168,1.585180,0.007845,1.033487
2,(other vegetables),(bottled water),0.193493,0.110524,0.024809,0.128219,1.160101,0.003424,1.020297
3,(bottled water),(other vegetables),0.110524,0.193493,0.024809,0.224471,1.160101,0.003424,1.039945
4,(rolls/buns),(bottled water),0.183935,0.110524,0.024199,0.131564,1.190373,0.003870,1.024228
...,...,...,...,...,...,...,...,...,...
121,"(other vegetables, whole milk)",(yogurt),0.074835,0.139502,0.022267,0.297554,2.132979,0.011828,1.225003
122,"(yogurt, whole milk)",(other vegetables),0.056024,0.193493,0.022267,0.397459,2.054131,0.011427,1.338511
123,(other vegetables),"(yogurt, whole milk)",0.193493,0.056024,0.022267,0.115081,2.054131,0.011427,1.066737
124,(yogurt),"(other vegetables, whole milk)",0.139502,0.074835,0.022267,0.159621,2.132979,0.011828,1.100890
125,(whole milk),"(other vegetables, yogurt)",0.255516,0.043416,0.022267,0.087147,2.007235,0.011174,1.047905